// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5k9CvrO_3O-lqoX4clvvvoDLpdht42Do',
    appId: '1:397274452252:web:61168112f424ad60bb6ad9',
    messagingSenderId: '397274452252',
    projectId: 'fir-project-bdac6',
    authDomain: 'fir-project-bdac6.firebaseapp.com',
    storageBucket: 'fir-project-bdac6.firebasestorage.app',
    measurementId: 'G-RC1MGMZPVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFBL61JP-Zww795WTK_SPpa_SBlX0Wkds',
    appId: '1:397274452252:android:c59702c376f2500bbb6ad9',
    messagingSenderId: '397274452252',
    projectId: 'fir-project-bdac6',
    storageBucket: 'fir-project-bdac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnG4RaMwRoQPVAqJ6bTsfkF--1Y3fXYFo',
    appId: '1:397274452252:ios:74e1f6e5a783ff9cbb6ad9',
    messagingSenderId: '397274452252',
    projectId: 'fir-project-bdac6',
    storageBucket: 'fir-project-bdac6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnG4RaMwRoQPVAqJ6bTsfkF--1Y3fXYFo',
    appId: '1:397274452252:ios:74e1f6e5a783ff9cbb6ad9',
    messagingSenderId: '397274452252',
    projectId: 'fir-project-bdac6',
    storageBucket: 'fir-project-bdac6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5k9CvrO_3O-lqoX4clvvvoDLpdht42Do',
    appId: '1:397274452252:web:02f6fb4d96082028bb6ad9',
    messagingSenderId: '397274452252',
    projectId: 'fir-project-bdac6',
    authDomain: 'fir-project-bdac6.firebaseapp.com',
    storageBucket: 'fir-project-bdac6.firebasestorage.app',
    measurementId: 'G-ZSXQ6WE157',
  );
}
